[".local/.oh-my-tmux"]
type = "archive"
url = "https://github.com/gpakosz/.tmux/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

# JetBrains Mono Nerd Font - download archive but only extract Mono variants
[".local/share/fonts"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip"
include = ["**/JetBrainsMonoNerdFontMono-*.ttf"]
refreshPeriod = "720h"
